#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libfprint
Version  : 1.90.1
Release  : 6
URL      : https://gitlab.freedesktop.org/libfprint/libfprint/-/archive/v1.90.1/libfprint-v1.90.1.tar.gz
Source0  : https://gitlab.freedesktop.org/libfprint/libfprint/-/archive/v1.90.1/libfprint-v1.90.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: libfprint-config = %{version}-%{release}
Requires: libfprint-data = %{version}-%{release}
Requires: libfprint-lib = %{version}-%{release}
Requires: libfprint-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : cmake
BuildRequires : docbook-xml
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : libxslt
BuildRequires : nss-dev
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gusb)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pkgconfig(xv)
BuildRequires : valgrind

%description
libfprint
=========
libfprint is part of the fprint project:
https://fprint.freedesktop.org/

%package config
Summary: config components for the libfprint package.
Group: Default

%description config
config components for the libfprint package.


%package data
Summary: data components for the libfprint package.
Group: Data

%description data
data components for the libfprint package.


%package dev
Summary: dev components for the libfprint package.
Group: Development
Requires: libfprint-lib = %{version}-%{release}
Requires: libfprint-data = %{version}-%{release}
Provides: libfprint-devel = %{version}-%{release}
Requires: libfprint = %{version}-%{release}

%description dev
dev components for the libfprint package.


%package doc
Summary: doc components for the libfprint package.
Group: Documentation

%description doc
doc components for the libfprint package.


%package lib
Summary: lib components for the libfprint package.
Group: Libraries
Requires: libfprint-data = %{version}-%{release}
Requires: libfprint-license = %{version}-%{release}

%description lib
lib components for the libfprint package.


%package license
Summary: license components for the libfprint package.
Group: Default

%description license
license components for the libfprint package.


%prep
%setup -q -n libfprint-v1.90.1
cd %{_builddir}/libfprint-v1.90.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586066210
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/libfprint
cp %{_builddir}/libfprint-v1.90.1/COPYING %{buildroot}/usr/share/package-licenses/libfprint/caeb68c46fa36651acf592771d09de7937926bb3
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/60-libfprint-2-autosuspend.rules

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/FPrint-2.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/libfprint-2/fp-context.h
/usr/include/libfprint-2/fp-device.h
/usr/include/libfprint-2/fp-enums.h
/usr/include/libfprint-2/fp-image-device.h
/usr/include/libfprint-2/fp-image.h
/usr/include/libfprint-2/fp-print.h
/usr/include/libfprint-2/fprint.h
/usr/lib64/libfprint-2.so
/usr/lib64/pkgconfig/libfprint-2.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/libfprint-2/advanced-topics.html
/usr/share/gtk-doc/html/libfprint-2/api-index.html
/usr/share/gtk-doc/html/libfprint-2/deprecated-api-index.html
/usr/share/gtk-doc/html/libfprint-2/driver-dev.html
/usr/share/gtk-doc/html/libfprint-2/driver-helpers.html
/usr/share/gtk-doc/html/libfprint-2/driver-img.html
/usr/share/gtk-doc/html/libfprint-2/driver-misc.html
/usr/share/gtk-doc/html/libfprint-2/driver-print.html
/usr/share/gtk-doc/html/libfprint-2/getting-started.html
/usr/share/gtk-doc/html/libfprint-2/home.png
/usr/share/gtk-doc/html/libfprint-2/index.html
/usr/share/gtk-doc/html/libfprint-2/intro.html
/usr/share/gtk-doc/html/libfprint-2/left-insensitive.png
/usr/share/gtk-doc/html/libfprint-2/left.png
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-FpContext.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-FpDevice.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-FpImage.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-FpImageDevice.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-FpPrint.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-Image-frame-assembly.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-Internal-FpImage.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-Internal-FpPrint.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-Logging.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-Sequential-state-machine.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-USB-transfer-helpers.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-fp-device.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-fpi-context.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2.devhelp2
/usr/share/gtk-doc/html/libfprint-2/pt01.html
/usr/share/gtk-doc/html/libfprint-2/pt02.html
/usr/share/gtk-doc/html/libfprint-2/pt03.html
/usr/share/gtk-doc/html/libfprint-2/right-insensitive.png
/usr/share/gtk-doc/html/libfprint-2/right.png
/usr/share/gtk-doc/html/libfprint-2/style.css
/usr/share/gtk-doc/html/libfprint-2/up-insensitive.png
/usr/share/gtk-doc/html/libfprint-2/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libfprint-2.so.2
/usr/lib64/libfprint-2.so.2.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libfprint/caeb68c46fa36651acf592771d09de7937926bb3
