#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v21
# autospec commit: be3faa5
#
Name     : libfprint
Version  : 1.94.9
Release  : 6
URL      : https://gitlab.freedesktop.org/libfprint/libfprint/-/archive/v1.94.9/libfprint-v1.94.9.tar.gz
Source0  : https://gitlab.freedesktop.org/libfprint/libfprint/-/archive/v1.94.9/libfprint-v1.94.9.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: libfprint-config = %{version}-%{release}
Requires: libfprint-data = %{version}-%{release}
Requires: libfprint-lib = %{version}-%{release}
Requires: libfprint-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : cairo-dev
BuildRequires : docbook-xml
BuildRequires : glib-dev
BuildRequires : gtk-doc
BuildRequires : libgudev-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-introspection-1.0)
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(gusb)
BuildRequires : valgrind
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
These are example images from NIST and are in the public domain.
The PNG files have been generated by using the greyscale data as a mask.

%package config
Summary: config components for the libfprint package.
Group: Default

%description config
config components for the libfprint package.


%package data
Summary: data components for the libfprint package.
Group: Data

%description data
data components for the libfprint package.


%package dev
Summary: dev components for the libfprint package.
Group: Development
Requires: libfprint-lib = %{version}-%{release}
Requires: libfprint-data = %{version}-%{release}
Provides: libfprint-devel = %{version}-%{release}
Requires: libfprint = %{version}-%{release}

%description dev
dev components for the libfprint package.


%package doc
Summary: doc components for the libfprint package.
Group: Documentation

%description doc
doc components for the libfprint package.


%package lib
Summary: lib components for the libfprint package.
Group: Libraries
Requires: libfprint-data = %{version}-%{release}
Requires: libfprint-license = %{version}-%{release}

%description lib
lib components for the libfprint package.


%package license
Summary: license components for the libfprint package.
Group: Default

%description license
license components for the libfprint package.


%package tests
Summary: tests components for the libfprint package.
Group: Default
Requires: libfprint = %{version}-%{release}

%description tests
tests components for the libfprint package.


%prep
%setup -q -n libfprint-v1.94.9
cd %{_builddir}/libfprint-v1.94.9
pushd ..
cp -a libfprint-v1.94.9 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1741283462
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs
cd ../buildavx2;
meson test -C builddir --print-errorlogs || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/libfprint
cp %{_builddir}/libfprint-v%{version}/COPYING %{buildroot}/usr/share/package-licenses/libfprint/caeb68c46fa36651acf592771d09de7937926bb3 || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/70-libfprint-2.rules

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/FPrint-2.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/metainfo/org.freedesktop.libfprint.metainfo.xml

%files dev
%defattr(-,root,root,-)
/usr/include/libfprint-2/fp-context.h
/usr/include/libfprint-2/fp-device.h
/usr/include/libfprint-2/fp-enums.h
/usr/include/libfprint-2/fp-image-device.h
/usr/include/libfprint-2/fp-image.h
/usr/include/libfprint-2/fp-print.h
/usr/include/libfprint-2/fprint.h
/usr/lib64/libfprint-2.so
/usr/lib64/pkgconfig/libfprint-2.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/libfprint-2/FpContext.html
/usr/share/gtk-doc/html/libfprint-2/FpDevice.html
/usr/share/gtk-doc/html/libfprint-2/FpImage.html
/usr/share/gtk-doc/html/libfprint-2/FpImageDevice.html
/usr/share/gtk-doc/html/libfprint-2/FpPrint.html
/usr/share/gtk-doc/html/libfprint-2/advanced-topics.html
/usr/share/gtk-doc/html/libfprint-2/api-index.html
/usr/share/gtk-doc/html/libfprint-2/deprecated-api-index.html
/usr/share/gtk-doc/html/libfprint-2/driver-dev.html
/usr/share/gtk-doc/html/libfprint-2/driver-helpers.html
/usr/share/gtk-doc/html/libfprint-2/driver-img.html
/usr/share/gtk-doc/html/libfprint-2/driver-misc.html
/usr/share/gtk-doc/html/libfprint-2/driver-print.html
/usr/share/gtk-doc/html/libfprint-2/getting-started.html
/usr/share/gtk-doc/html/libfprint-2/home.png
/usr/share/gtk-doc/html/libfprint-2/index.html
/usr/share/gtk-doc/html/libfprint-2/intro.html
/usr/share/gtk-doc/html/libfprint-2/left-insensitive.png
/usr/share/gtk-doc/html/libfprint-2/left.png
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-Image-frame-assembly.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-Internal-FpDevice.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-Internal-FpImage.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-Internal-FpImageDevice.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-Internal-FpPrint.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-Logging.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-SPI-transfer-helpers.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-Sequential-state-machine.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-USB-transfer-helpers.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2-fpi-context.html
/usr/share/gtk-doc/html/libfprint-2/libfprint-2.devhelp2
/usr/share/gtk-doc/html/libfprint-2/pt01.html
/usr/share/gtk-doc/html/libfprint-2/pt02.html
/usr/share/gtk-doc/html/libfprint-2/pt03.html
/usr/share/gtk-doc/html/libfprint-2/right-insensitive.png
/usr/share/gtk-doc/html/libfprint-2/right.png
/usr/share/gtk-doc/html/libfprint-2/style.css
/usr/share/gtk-doc/html/libfprint-2/up-insensitive.png
/usr/share/gtk-doc/html/libfprint-2/up.png

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libfprint-2.so.2.0.0
/usr/lib64/libfprint-2.so.2
/usr/lib64/libfprint-2.so.2.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libfprint/caeb68c46fa36651acf592771d09de7937926bb3

%files tests
%defattr(-,root,root,-)
/V3/usr/libexec/installed-tests/libfprint-2/test-fpi-assembling
/V3/usr/libexec/installed-tests/libfprint-2/test-fpi-device
/V3/usr/libexec/installed-tests/libfprint-2/test-fpi-ssm
/usr/libexec/installed-tests/libfprint-2/capture.py
/usr/libexec/installed-tests/libfprint-2/test-fpi-assembling
/usr/libexec/installed-tests/libfprint-2/test-fpi-device
/usr/libexec/installed-tests/libfprint-2/test-fpi-ssm
/usr/libexec/installed-tests/libfprint-2/umockdev-test.py
/usr/share/installed-tests/libfprint-2/aes2501/capture.pcapng
/usr/share/installed-tests/libfprint-2/aes2501/capture.png
/usr/share/installed-tests/libfprint-2/aes2501/device
/usr/share/installed-tests/libfprint-2/aes3500/capture.ioctl
/usr/share/installed-tests/libfprint-2/aes3500/capture.png
/usr/share/installed-tests/libfprint-2/aes3500/device
/usr/share/installed-tests/libfprint-2/driver-aes2501.test
/usr/share/installed-tests/libfprint-2/driver-aes3500.test
/usr/share/installed-tests/libfprint-2/driver-egis0570.test
/usr/share/installed-tests/libfprint-2/driver-egismoc-0586.test
/usr/share/installed-tests/libfprint-2/driver-egismoc-0587.test
/usr/share/installed-tests/libfprint-2/driver-egismoc-05a1.test
/usr/share/installed-tests/libfprint-2/driver-egismoc.test
/usr/share/installed-tests/libfprint-2/driver-elan-cobo.test
/usr/share/installed-tests/libfprint-2/driver-elan.test
/usr/share/installed-tests/libfprint-2/driver-elanmoc.test
/usr/share/installed-tests/libfprint-2/driver-elanspi.test
/usr/share/installed-tests/libfprint-2/driver-focaltech_moc.test
/usr/share/installed-tests/libfprint-2/driver-fpcmoc.test
/usr/share/installed-tests/libfprint-2/driver-goodixmoc.test
/usr/share/installed-tests/libfprint-2/driver-nb1010.test
/usr/share/installed-tests/libfprint-2/driver-realtek-5816.test
/usr/share/installed-tests/libfprint-2/driver-realtek.test
/usr/share/installed-tests/libfprint-2/driver-synaptics.test
/usr/share/installed-tests/libfprint-2/driver-upektc_img-tcs1s.test
/usr/share/installed-tests/libfprint-2/driver-upektc_img.test
/usr/share/installed-tests/libfprint-2/driver-uru4000-4500.test
/usr/share/installed-tests/libfprint-2/driver-uru4000-msv2.test
/usr/share/installed-tests/libfprint-2/driver-vfs0050.test
/usr/share/installed-tests/libfprint-2/driver-vfs301.test
/usr/share/installed-tests/libfprint-2/driver-vfs5011.test
/usr/share/installed-tests/libfprint-2/driver-vfs7552.test
/usr/share/installed-tests/libfprint-2/egis0570/capture.pcapng
/usr/share/installed-tests/libfprint-2/egis0570/capture.png
/usr/share/installed-tests/libfprint-2/egis0570/device
/usr/share/installed-tests/libfprint-2/egismoc-0586/custom.pcapng
/usr/share/installed-tests/libfprint-2/egismoc-0586/custom.py
/usr/share/installed-tests/libfprint-2/egismoc-0586/device
/usr/share/installed-tests/libfprint-2/egismoc-0587/custom.pcapng
/usr/share/installed-tests/libfprint-2/egismoc-0587/custom.py
/usr/share/installed-tests/libfprint-2/egismoc-0587/device
/usr/share/installed-tests/libfprint-2/egismoc-05a1/custom.pcapng
/usr/share/installed-tests/libfprint-2/egismoc-05a1/custom.py
/usr/share/installed-tests/libfprint-2/egismoc-05a1/device
/usr/share/installed-tests/libfprint-2/egismoc/custom.pcapng
/usr/share/installed-tests/libfprint-2/egismoc/custom.py
/usr/share/installed-tests/libfprint-2/egismoc/device
/usr/share/installed-tests/libfprint-2/elan-cobo/capture.pcapng
/usr/share/installed-tests/libfprint-2/elan-cobo/capture.png
/usr/share/installed-tests/libfprint-2/elan-cobo/device
/usr/share/installed-tests/libfprint-2/elan/capture.ioctl
/usr/share/installed-tests/libfprint-2/elan/capture.ioctl-recording
/usr/share/installed-tests/libfprint-2/elan/capture.png
/usr/share/installed-tests/libfprint-2/elan/device
/usr/share/installed-tests/libfprint-2/elanmoc/custom.pcapng
/usr/share/installed-tests/libfprint-2/elanmoc/custom.py
/usr/share/installed-tests/libfprint-2/elanmoc/device
/usr/share/installed-tests/libfprint-2/elanspi/capture.ioctl
/usr/share/installed-tests/libfprint-2/elanspi/capture.png
/usr/share/installed-tests/libfprint-2/elanspi/device-hidraw
/usr/share/installed-tests/libfprint-2/elanspi/device-spi
/usr/share/installed-tests/libfprint-2/focaltech_moc/custom.pcapng
/usr/share/installed-tests/libfprint-2/focaltech_moc/custom.py
/usr/share/installed-tests/libfprint-2/focaltech_moc/device
/usr/share/installed-tests/libfprint-2/fpcmoc/custom.pcapng
/usr/share/installed-tests/libfprint-2/fpcmoc/custom.py
/usr/share/installed-tests/libfprint-2/fpcmoc/device
/usr/share/installed-tests/libfprint-2/fpi-assembling.test
/usr/share/installed-tests/libfprint-2/fpi-device.test
/usr/share/installed-tests/libfprint-2/fpi-ssm.test
/usr/share/installed-tests/libfprint-2/goodixmoc/custom.pcapng
/usr/share/installed-tests/libfprint-2/goodixmoc/custom.py
/usr/share/installed-tests/libfprint-2/goodixmoc/device
/usr/share/installed-tests/libfprint-2/nb1010/capture.ioctl
/usr/share/installed-tests/libfprint-2/nb1010/capture.png
/usr/share/installed-tests/libfprint-2/nb1010/device
/usr/share/installed-tests/libfprint-2/prints/README
/usr/share/installed-tests/libfprint-2/prints/arch.jpg
/usr/share/installed-tests/libfprint-2/prints/arch.png
/usr/share/installed-tests/libfprint-2/prints/loop-right.jpg
/usr/share/installed-tests/libfprint-2/prints/loop-right.png
/usr/share/installed-tests/libfprint-2/prints/tented_arch.jpg
/usr/share/installed-tests/libfprint-2/prints/tented_arch.png
/usr/share/installed-tests/libfprint-2/prints/whorl.jpg
/usr/share/installed-tests/libfprint-2/prints/whorl.png
/usr/share/installed-tests/libfprint-2/realtek-5816/custom.pcapng
/usr/share/installed-tests/libfprint-2/realtek-5816/custom.py
/usr/share/installed-tests/libfprint-2/realtek-5816/device
/usr/share/installed-tests/libfprint-2/realtek/custom.pcapng
/usr/share/installed-tests/libfprint-2/realtek/custom.py
/usr/share/installed-tests/libfprint-2/realtek/device
/usr/share/installed-tests/libfprint-2/synaptics/custom.pcapng
/usr/share/installed-tests/libfprint-2/synaptics/custom.py
/usr/share/installed-tests/libfprint-2/synaptics/device
/usr/share/installed-tests/libfprint-2/upektc_img-tcs1s/capture.pcapng
/usr/share/installed-tests/libfprint-2/upektc_img-tcs1s/capture.png
/usr/share/installed-tests/libfprint-2/upektc_img-tcs1s/device
/usr/share/installed-tests/libfprint-2/upektc_img/capture.pcapng
/usr/share/installed-tests/libfprint-2/upektc_img/capture.png
/usr/share/installed-tests/libfprint-2/upektc_img/device
/usr/share/installed-tests/libfprint-2/uru4000-4500/capture.pcapng
/usr/share/installed-tests/libfprint-2/uru4000-4500/capture.png
/usr/share/installed-tests/libfprint-2/uru4000-4500/device
/usr/share/installed-tests/libfprint-2/uru4000-msv2/capture.pcapng
/usr/share/installed-tests/libfprint-2/uru4000-msv2/capture.png
/usr/share/installed-tests/libfprint-2/uru4000-msv2/device
/usr/share/installed-tests/libfprint-2/vfs0050/capture-recorded.ioctl
/usr/share/installed-tests/libfprint-2/vfs0050/capture.ioctl
/usr/share/installed-tests/libfprint-2/vfs0050/capture.png
/usr/share/installed-tests/libfprint-2/vfs0050/device
/usr/share/installed-tests/libfprint-2/vfs301/capture-recorded.ioctl
/usr/share/installed-tests/libfprint-2/vfs301/capture.ioctl
/usr/share/installed-tests/libfprint-2/vfs301/capture.png
/usr/share/installed-tests/libfprint-2/vfs301/device
/usr/share/installed-tests/libfprint-2/vfs5011/capture.ioctl
/usr/share/installed-tests/libfprint-2/vfs5011/capture.png
/usr/share/installed-tests/libfprint-2/vfs5011/device
/usr/share/installed-tests/libfprint-2/vfs7552/capture.ioctl
/usr/share/installed-tests/libfprint-2/vfs7552/capture.png
/usr/share/installed-tests/libfprint-2/vfs7552/device
